CREATE TABLE CARS (
    ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    COLOR VARCHAR(32),
    MODEL VARCHAR(32),
    PAYMENT DECIMAL(10,2),
    LICENSE_PLATE VARCHAR(20),
    STATUS BOOLEAN
);

CREATE TABLE CUSTOMERS (
    ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    ADDRESS VARCHAR(100),
    PHONE_NUMBER VARCHAR(32),
    DRIVERS_LICENSE VARCHAR(20),
    STATUS BOOLEAN
);

CREATE TABLE RENTS (
    ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    CAR INTEGER NOT NULL REFERENCES CARS(ID) ON DELETE CASCADE,
    CUSTOMER INTEGER NOT NULL REFERENCES CUSTOMERS(ID) ON DELETE CASCADE,
    RENT_DATE DATE,
    DUE_DATE DATE
);