CREATE TABLE CARS (
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    COLOR VARCHAR(32),
    MODEL VARCHAR(32),
    PAYMENT DECIMAL(10,2),
    LICENSE_PLATE VARCHAR(20),
    STATUS BOOLEAN
);

CREATE TABLE CUSTOMERS (
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    ADDRESS VARCHAR(100),
    PHONE_NUMBER VARCHAR(32),
    DRIVERS_LICENSE VARCHAR(20),
    STATUS BOOLEAN
);

CREATE TABLE RENTS (
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    CAR VARCHAR(36) NOT NULL REFERENCES CARS(ID) ON DELETE CASCADE,
    CUSTOMER VARCHAR(36) NOT NULL REFERENCES CUSTOMERS(ID) ON DELETE CASCADE,
    RENT_DATE DATE,
    DUE_DATE DATE
);