-- PostgreSQL initialization script for Car Rental Database
-- Creates the schema and initializes tables with UUID IDs

-- Create CUSTOMERS table
CREATE TABLE CUSTOMERS (
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    ADDRESS VARCHAR(100),
    PHONE_NUMBER VARCHAR(32),
    DRIVERS_LICENSE VARCHAR(20),
    STATUS BOOLEAN
);

-- Create CARS table
CREATE TABLE CARS (
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    COLOR VARCHAR(32),
    MODEL VARCHAR(32),
    PAYMENT DECIMAL(10,2),
    LICENSE_PLATE VARCHAR(20),
    STATUS BOOLEAN
);

-- Create RENTS table
CREATE TABLE RENTS (
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    CAR VARCHAR(36) NOT NULL REFERENCES CARS(ID) ON DELETE CASCADE,
    CUSTOMER VARCHAR(36) NOT NULL REFERENCES CUSTOMERS(ID) ON DELETE CASCADE,
    RENT_DATE DATE,
    DUE_DATE DATE
);

-- Create indexes for performance
CREATE INDEX idx_customer_name ON CUSTOMERS(LAST_NAME, FIRST_NAME);
CREATE INDEX idx_car_license ON CARS(LICENSE_PLATE);
CREATE INDEX idx_rent_car ON RENTS(CAR);
CREATE INDEX idx_rent_customer ON RENTS(CUSTOMER);
CREATE INDEX idx_rent_dates ON RENTS(RENT_DATE, DUE_DATE);
